### ISSUE TITLE
Fix leak action

### ISSUE THREAD

**Issue by rznn7** [rznn7/pixel-game-jam-2024-rvg#11]
A leak can be fix while in the cockpit
It costs 1 Power  and reduces the leakage by 15%.

**Comment by GoldenPike06** [comment]
Player can press leak icon to fix the leak via interaction
Takes 2 power and 1 scrap to fix by 15%.

To do:
Implement case where it doesn't fix a leak if it's at 0% (resources are wasted)
Make icon button UI easier to interact with (gray highlight on button makes it hard to see)

**Comment by GoldenPike06** [comment]
Implemented case where resources are not wasted if leak at 0%
Created interaction to handle 0% leak status

To do:
Make icon button UI easier to interact with (gray highlight on button makes it hard to see)

**Comment by GoldenPike06** [comment]
Fixed UI interaction highlight
